# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "vStone/centos-7.x-puppet.3.x"
  config.vm.hostname = "omd-box"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.51.105"
 
  config.vm.synced_folder "../../", "/vshare/", create: true

  config.vm.provision :shell, inline: "/vshare/scripts/vm-initial-setup/basicInstallations.sh", privileged: true
  config.vm.provision :shell, inline: "/vshare/scripts/vm-initial-setup/createSharedDirectories.sh", privileged: true
  config.vm.provision "shell", inline: "cp /vshare/scripts/omd_seup/* /mnt/gluster/repo/", privileged: true
 
  #OMD Files // execute
  config.vm.provision :shell, inline: "/vshare/scripts/omd_seup/omdserversetuponcentos.sh", privileged: true
  config.vm.provision "shell", inline: "systemctl stop firewalld", privileged: true
end
