# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.hostname = "ELK-box"
  config.vm.box_check_update = false

if ENV['IMAGE_FILE'] != "use-image-from-local-machine"
	config.vm.box = "vStone/centos-7.x-puppet.3.x"
else
	config.vm.box = "../../base-images/centos-7.x-64bit-puppet.3.x-vbox.5.0.0.1.box"
end

if ENV['ENV_TYPE'] != "local"
	config.vm.network  "public_network", bridge: ENV['NET_CONFIG_FILE'], ip: ENV['SYS_IP']
else
	config.vm.network "private_network", ip: ENV['SYS_IP']
end

   config.vm.provider "virtualbox" do |vb|
   	vb.gui = true
   end


  config.vm.synced_folder "../../", "/vshare/", create: true

 config.vm.provision :shell, inline: "/vshare/scripts/vm-initial-setup/basicInstallations.sh", privileged: true
 config.vm.provision :shell, inline: "/vshare/scripts/vm-initial-setup/createSharedDirectories.sh", privileged: true

  #ELK Files copy
 config.vm.provision "shell", inline: "cp /vshare/scripts/elk_setup/centos/* /mnt/gluster/repo/", privileged: true

 #ELK Files // execute
 config.vm.provision :shell, inline:"cd /vshare/scripts/elk_setup/centos/ && ./elksetupupdate.sh", privileged: false
 config.vm.provision "shell", inline: "systemctl stop firewalld", privileged: true


end
