# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "vStone/centos-7.x-puppet.3.x"
  config.vm.hostname = "ELK-box"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.51.102"
  #config.vm.network  "public_network", bridge: 'eth1', ip: ENV['SYS_IP'] 
   
   config.vm.provider "virtualbox" do |vb|
   	vb.gui = true
   end
 
  
  config.vm.synced_folder "../../", "/vshare/", create: true

 config.vm.provision :shell, inline: "/vshare/scripts/vm-initial-setup/basicInstallations.sh", privileged: true
 config.vm.provision :shell, inline: "/vshare/scripts/vm-initial-setup/createSharedDirectories.sh", privileged: true

  #ELK Files copy
 config.vm.provision "shell", inline: "cp /vshare/scripts/elk_setup/centos/* /mnt/gluster/repo/", privileged: true
 
 #ELK Files // execute
 config.vm.provision :shell, inline:"cd /vshare/scripts/elk_setup/centos/ && ./elksetupupdate.sh", privileged: false
 config.vm.provision "shell", inline: "systemctl stop firewalld", privileged: true
 
  
end
