# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.hostname = "NF-BOX"
  config.vm.box_check_update = false

if ENV['IMAGE_FILE'] != "use-local-image"
	config.vm.box = "vStone/centos-7.x-puppet.3.x"
else
	config.vm.box = "../../repo/centos/centos-7.x-64bit-puppet.3.x-vbox.5.0.0.1.box"
end

 if ENV['ENV_TYPE'] != "local"
	config.vm.network  "public_network", bridge: ENV['NET_CONFIG_FILE'], ip: ENV['SYS_IP']
else
	config.vm.network "private_network", ip: ENV['SYS_IP']
end


  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = "1"
  end

  config.vm.synced_folder "../../", "/vshare/", create: true

  # Execute File
  config.vm.provision :shell, inline: "/vshare/scripts/vm-initial-setup/basicInstallations.sh", privileged: true
  config.vm.provision :shell, inline: "/vshare/scripts/vm-initial-setup/createSharedDirectories.sh", privileged: true
	config.vm.provision "shell", inline: "cp /vshare/scripts/vm-initial-setup/disable-system-ctl-firewalld.sh /etc/init.d/", privileged: true

  #copying config files to mount server share folder
  config.vm.provision "shell", inline: "cp -r /vshare/scripts/nf_test_server/* /mnt/gluster/repo/", privileged: true

  # Execute File
  config.vm.provision :shell, inline: "/vshare/scripts/nf_test_server/jmeter_setup.sh", privileged: true
  config.vm.provision :shell, inline:"/vshare/scripts/nf_test_server/collectd_setup.sh", privileged: true
  config.vm.provision :shell, inline:"/vshare/scripts/nf_test_server/influxdb_setup.sh", privileged: true
  config.vm.provision :shell, inline:"/vshare/scripts/nf_test_server/grafana_setup.sh", privileged: true
  config.vm.provision :shell, inline:"/vshare/scripts/nf_test_server/setdash_link.sh", privileged: true
  config.vm.provision :shell, inline:"/vshare/scripts/nf_test_server/owaspZAP_setup.sh", privileged: true
  config.vm.provision :shell, inline:"/vshare/scripts/nf_test_server/util_setup.sh", privileged: true
  config.vm.provision :shell, inline:"/vshare/scripts/nf_test_server/dashborad_setup.sh", privileged: true

  # Execute File
  #config.vm.provision :shell, inline:"/vshare/scripts/nf_test_server/service_re-startability.sh", privileged: true

  # Execute Stop Firewall
  config.vm.provision "shell", inline: "systemctl stop firewalld", privileged: true
  config.vm.provision "shell", inline: "systemctl disable firewalld", privileged: true

end
