# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "vStone/centos-7.x-puppet.3.x"
  config.vm.hostname = "Jenkins-box"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.51.103"
  config.vm.synced_folder "vshare", "/vshare", create: true

  config.vm.provision :shell, inline: "/vshare/scripts/basicInstallations.sh", privileged: true
  config.vm.provision :shell, inline: "/vshare/scripts/createSharedDirectories.sh", privileged: true
  config.vm.provision :shell, inline:"/vshare/scripts/jenkins-setup/jenkinssetup_centos.sh", privileged: true
  config.vm.provision "shell", inline: "cp /vshare/scripts/sonar-setup/* /mnt/gluster/repo/", privileged: true
  config.vm.provision :shell, inline: "/vshare/scripts/sonar-setup/sonarsetup.sh", privileged: true
  config.vm.provision "shell", inline: "systemctl stop firewalld", privileged: true
 
end
